# Generated by cucumber-sinatra. (2012-04-30 22:16:20 -0300)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'application.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = MyApplication

class MyApplicationWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  MyApplicationWorld.new
end
